### ISSUE TITLE
Conformability Error for moderately large dataset

### ISSUE THREAD

**Issue by rdisalv2** [ukmueller/SCPC#1]
Dear Professor Müller and other package maintainers,

Thank you for writing this package! I am facing a technical issue. I am finding that the scpc command does not work for moderately large datasets (error copied below). I know scpc uses a different algorithm for datasets larger than 4500 observations, so maybe this is related? 

When I run scpc with N=6381, I get this error

              LNgetOms():  3200  conformability error
             set_ccspc():     -  function returned error
      set_Wx_nocluster():     -  function returned error
                 <istmt>:     -  function returned error

When I run it on N=3025 (randomly sampled from the larger one), it works.

Thanks so much, and let me know if you would like me to share my data and code (the data is public so it would not be a problem).

Richard

**Comment by ukmueller** [comment]
Fixed now, thank you for bringing it to my attention.

**Comment by ukmueller** [comment]
Hi Richard,

I fixed the issue. Thanks again for pointing it out!

Please let me know if you run into further trouble.

Best wishes,

Ulrich
